version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10-alpine
    env_file:
      - $ENV
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: deals_backend/
      dockerfile: Dockerfile
    env_file:
      - $ENV
    depends_on:
      - db
    volumes:
      - static:/backend_static/

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - backend
