# Generated by Django 4.2.3 on 2023-07-27 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.CharField(max_length=128, verbose_name="Логин покупателя"),
                ),
                (
                    "item",
                    models.CharField(
                        max_length=128, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1, message="Значение не может быть меньше 1"
                            )
                        ],
                        verbose_name="Сумма сделки",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1, message="Значение не может быть меньше 1"
                            )
                        ],
                        verbose_name="Количество товара",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
                "ordering": ["-date"],
            },
        ),
    ]
